### ISSUE TITLE
Wiki & test suites milestone0Tester.ps1

### ISSUE THREAD

**Issue by WilliamDelamare** [Estia-advanced-programming/pandora-public#105]
**Describe the bug**
* The message for the commit in the wiki for merging starter pack leads to an error (wrong command line format?): **solution**  copy the line until `theirs`
* The jar luanch line in the ps1 file leads to an error: **solution** remove `-Dfile.encoding=UTF-8`)

**Comment by dhmmasson** [comment]
- [x] Updated the doc to :
```bash
git fetch starterPack --prune
git merge starterPack/main -X theirs -m 'chore(update): merge modification from starter pack'
```

- [ ] transfer the issue to starterkit
