### ISSUE TITLE
Evaluation of milestones 1,2,3 

### ISSUE THREAD

**Issue by zazacito** [Estia-advanced-programming/pandora-public#39]
The Milestones Assessments and checks are impossible to run.
We get this error "The job was not started because the spending limit for Actions and Packages has been exceeded. ".
What should we do ?

![image](https://user-images.githubusercontent.com/61968508/77099912-03de9e00-6a15-11ea-8d17-48f0a6f97b11.png)

**Comment by WilliamDelamare** [comment]
Yes, sorry about that: we did not know there was a limitation for 'actions' on github. The automatic process is broken!

But you can still use this: https://github.com/Estia-advanced-programming/pandora-public/tree/master/testGenerator/autogradingGenerator/autograder/testsFiles
to check your code.

**Comment by dhmmasson** [comment]
I have updated the test suite.  200 tests files are available for milestone 1/2/3
