### ISSUE TITLE
Lien vers les fichiers tests vides

### ISSUE THREAD

**Issue by tibocbo** [Estia-advanced-programming/pandora-public#47]
**Describe the bug**
Le lien vers les fichiers tests renvoient vers une page vide

**To Reproduce**
1. Go to 'Pandora » Flight Records'
2. Click on 'Folder full of test files'
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/80093160/110129267-0d991700-7dc8-11eb-8900-d45a5b258e9c.png)

**Comment by dhmmasson** [comment]
Thank you @tibocbo 
Issue have been solved.
