### ISSUE TITLE
Error in the constant value "Earth radius"

### ISSUE THREAD

**Issue by xabadin** [Estia-advanced-programming/pandora-public#53]
The earth radius is wrong in the instructions :
![image](https://user-images.githubusercontent.com/80093086/110532514-364d4380-811d-11eb-8d2d-e47e89d362e0.png)
(It should be 6371km.)

We think that this wrong value may be used in your tests would it be possible to know if the value used is the good one or the wrong one?

**Comment by WilliamDelamare** [comment]
In English, the comma separates thousands, and the dot the decimals. For instance, `1,056,371.98 km`.

Still, we will check again in the tests to ensure there was no mistake.
