### ISSUE TITLE
Ouput numbers precision (0.01)

### ISSUE THREAD

**Issue by WilliamDelamare** [Estia-advanced-programming/pandora-public#54]
* This output constraints is not in the wiki (just in the 2020 Updates page)
* This ouptut is not set as an example in the pandora-starter pack source code (thus, all following copy/paste are not using the `String.format("%.2f", variableName);`, just the `String.valueOf(variableName);`

**Comment by dhmmasson** [comment]
- [ ] Update wiki
- [ ] Update pandora-template

**Comment by dhmmasson** [comment]
Change the tester to take into account the rounding as weelll
