### ISSUE TITLE
flighDuration 'a3' Outputs 0 

### ISSUE THREAD

**Issue by xabadin** [Estia-advanced-programming/pandora-public#57]
I think that there is a problem with the Output flightDuration : 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/80093086/112159845-db6e1e80-8be9-11eb-8bfd-089996171ef0.png)
As you can see the Output is correct in the console but the test shows 0 as Output: 
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/80093086/112159943-f8a2ed00-8be9-11eb-9beb-da89749982b0.png)
Whereas, the first batch of test is working fine :
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/80093086/112160081-1c663300-8bea-11eb-8e51-3916fba540fa.png)

**Comment by WilliamDelamare** [comment]
Do you have access to the actual test files? (e.g., 0_101_MiG-29A.csv)
If yes, what is your output if not `0`? (not sure what you are showing in your console)

**Comment by xabadin** [comment]
In my console the output is 00:11:52 but in the test it shows 0. That's why I don't really understand what is going on.

And the picture of the console (the first one) is coming from the current test files ("0_201_MiG-23MLD.csv").

**Comment by dhmmasson** [comment]
Bug Confirmed against the teacher version.  
I'll fix it

**Comment by dhmmasson** [comment]
Found the error in the parsing of the full output. I split the line around the colon, the flight duration format is HH:mm:ss 
```javascript 
/**
 * fullReportClean - description
 *
 * @param  {string} fullReport multiline string
 * @return {object}            object Feature:value
 */
export function fullReportClean( fullReport ) {
  return fullReport.split( "\n" )
    .map( e => e.split( /:\s*/ ) )
    .reduce(
      ( cleanReport, featureValue ) => {
        cleanReport[ featureValue[ 0 ] ] = featureValue[ 1 ] !== undefined ? cleanOutput( featureValue[ 1 ] ) : null ;
        return cleanReport ;
      }, {}
    ) ;
}
```
