### ISSUE TITLE
Exercice 1_Tutorial_Eclipse_error to do running Pandore

### ISSUE THREAD

**Issue by Mazaud501** [Estia-advanced-programming/pandora-public#65]
**Describe the bug**
Afin de faire le running du test  de Pandore comme indiquer dans le tutoriel voir image suivante :
![image](https://user-images.githubusercontent.com/101091676/157017052-1273364f-9a25-4748-8faf-491dc012f533.png)
Il y a un problème qui vous sera indiquer comme non gérer par Eclipse dans la console.

**To Reproduce**
1.In _"Analysis.java"_ Go to line 54, 51 and 17, you must change "int" in front of "flightDuration" to "float" or double.
![image](https://user-images.githubusercontent.com/101091676/157017697-766ffa0b-8afa-4275-80a9-8b15f24a30b2.png)
![image](https://user-images.githubusercontent.com/101091676/157017753-4ed0ba0c-5972-4dc1-a93b-fd5226ec4597.png)

To remplace by:
![image](https://user-images.githubusercontent.com/101091676/157017843-602c927c-7c9c-4fb2-b79e-83853e6af578.png)
![image](https://user-images.githubusercontent.com/101091676/157017877-91b20749-41bb-48e1-8aee-8e3bc4551630.png)

2. Save the modification.
3. After you launch running
4. Finally you can see the result 

![image](https://user-images.githubusercontent.com/101091676/157018026-3955e01d-25a8-4208-8c2b-9e7d77c3a47a.png)

**Comment by dhmmasson** [comment]
Ok noted, All teams will see a Patch that solve the issue if they haven't followed your description

@Mazaud501 : next time describe what is the problem : 
- The program displays ```ERROR: Unhandled error ``` when launched for the first time
- Source of the error : field int flightDuration should be a float or a double value 

- Proposed Fix
