### ISSUE TITLE
Proposition for the flightDistance calculus

### ISSUE THREAD

**Issue by Mazaud501** [Estia-advanced-programming/pandora-public#70]
Good day,

We had a proposition regarding the flight Distance calculus. In fact, until now we've been using the .get(i).getAltitude() to sum it with the earth radius and then apply to it the haversine formula. We think that using this method on big iterations would lead to miscalculations. Thus, we propose to move from a .get(i).getAltitude() to a ((.get(i+1).getAltitude() - .get(i).getAltitude())/2) as we would reduce those imprecisions.

We had a discussion with Mr. DELAMARE abou this proposition, hence, for further detail, please contact @WilliamDelamare.

Thanks.

**Comment by WilliamDelamare** [comment]
Nice enhancement proposition!

**Comment by WilliamDelamare** [comment]
Just add a clear schematic of the computation principles (arc + altitude + real distance
![20220404_105621](https://user-images.githubusercontent.com/14878561/161511180-02813842-a624-44d1-83f0-20be56fbf636.jpg)
)

**Comment by dhmmasson** [comment]
Already the case... 

otherwise vertical distance computation would fail...

In our code dist is already computed as : 
```java
			double diffAlt = cur.getAltitude() - prev.getAltitude();
			double dist = Math.sqrt(d*d + diffAlt * diffAlt);
```
